### ISSUE TITLE
Support for PRISM

### ISSUE THREAD

**Issue by Im-PJ** [damienaicheh/MvvmCodeGenerator#3]
I'm using Prism MVVM and I would like to know how this tool can help me with that.

**Comment by damienaicheh** [comment]
Prism is not supported yet, I will add it in a few week. You use Prism.Core as a base for your ViewModels right ?

**Comment by damienaicheh** [comment]
The version 1.1.0 now support Prism.Core that is the base for Prism ViewModels. You can now look at it!
